#stage 1
FROM python:3.9-slim AS builder

WORKDIR /app

COPY . .


RUN pip install - requirements.txt --target=/app/deps

#STATGE 2
FROM gcr.io/distroless/python3-debian12

WORKDIR /app

COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

ENV PYTHONPATH="/app/deps"

EXPOSE 5000

CMD ["python", "main.py"] 
  
  

  
